cargo-features = ["edition"]

[package]
name = "quickblocks-bounty"
version = "0.1.0"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]
edition = '2018'

[dependencies]
ethereum-types = "0.3.2"
wu-diff = "0.1.0"
tokio = "0.1.7"
hyper = "*"
hyper-tls = "*"
serde = "1.0.70"
serde_json = "1.0.24"
serde_derive = "1.0.70"
failure = "0.1.1"
toml = "0.4"
http = "0.1"
dirs = "1.0.2"
log = { version = "0.4.3", features = ["std", "serde"] }
env_logger = "0.5.11"
#for tests
regex = "*"
bytes = "*"
futures = "0.1.23"
